// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV1QIK7C3L16OmxRtSed2kApaWj3OyUhY',
    appId: '1:393478207746:web:c93ca05fdd0c8b2145ea1b',
    messagingSenderId: '393478207746',
    projectId: 'dab-6cfc3',
    authDomain: 'dab-6cfc3.firebaseapp.com',
    storageBucket: 'dab-6cfc3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9_7bJ_90rranri2aDlNuJ8I_xbfjR7ao',
    appId: '1:393478207746:android:4b03789d1216eaf945ea1b',
    messagingSenderId: '393478207746',
    projectId: 'dab-6cfc3',
    storageBucket: 'dab-6cfc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy62IX23zxtDvSu3XDQgwriPmXhShp6cM',
    appId: '1:393478207746:ios:fc43cffee288341145ea1b',
    messagingSenderId: '393478207746',
    projectId: 'dab-6cfc3',
    storageBucket: 'dab-6cfc3.appspot.com',
    iosBundleId: 'com.example.dab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy62IX23zxtDvSu3XDQgwriPmXhShp6cM',
    appId: '1:393478207746:ios:520fe105d9a4aa1945ea1b',
    messagingSenderId: '393478207746',
    projectId: 'dab-6cfc3',
    storageBucket: 'dab-6cfc3.appspot.com',
    iosBundleId: 'com.example.dab.RunnerTests',
  );
}
